### ISSUE TITLE
Set API URL in qualys.conf

### ISSUE THREAD

**Issue by rdrgporto** [tesla-consulting/qualysbeat#1]
Hi, everyone

I use the API `https://qualysapi.qualys.eu`. However, I have found out that **Qualysbeat** uses `https://qualysapi.qg2.apps.qualys.eu` by default. 

Is it possible to set API URL in **qualys.conf** ?

Thanks in advance,

Rodrigo

**Comment by tesla-consulting** [comment]
Hi @rdrgporto ,
a new version of QualysBeat has been released! [QualysBeat_v2](https://github.com/tesla-consulting/qualysbeat/tree/QualysBeat_v2)
In this one you can choose the Qualys's API URL through qualysbeat.yml file. 

We're glad to help you 🙂 !

**Comment by rdrgporto** [comment]
Hi, @tesla-consulting 

It works 😃 . Thank very much. 

👀 Sometimes, it shows an error about **a mapping parsing**, I am going to create an another [issue](https://github.com/tesla-consulting/qualysbeat/issues/2).
